if: tag IS present
language: generic
os: linux
dist: bionic
before_install:
- nvm install node
- node --version
install:
- npm install
before_script:
script:
- npm run compile
after_script:
- npm run deploy
